### ISSUE TITLE
[Feature] Favicon and title 

### ISSUE THREAD

**Issue by jsvigneshkanna** [eduardconstantin/Crypto-Rankings#11]
Description:

Need to change the website title to `Crypto Rankings` and add favicon which represents the crypto/ money (coin image)

Please assign this to my name, will work on it.
Please add `hacktoberfest` label to keep track of my contributions

**Comment by priyanshu6781** [comment]
Hey, I would like to work. Please assign me this task!!

**Comment by eduardconstantin** [comment]
@priyanshu6781 sorry but @jsvigneshkanna is already working on this issue
