### ISSUE TITLE
Add more than 3 cryptocurrencies

### ISSUE THREAD

**Issue by ann0nip** [eduardconstantin/Crypto-Rankings#3]
I am thinking of adding a select list with the first 100 cryptocurrencies ordered by market cap, and the user can add new Card information about that crypto added.

**Comment by eduardconstantin** [comment]
Nice, great idea. But keep the top 3 on the top. Thank you!

**Comment by ethmtrgt** [comment]
Hello @ann0nip,
Are you working on this?

**Comment by ann0nip** [comment]
> ethmtrgt

I don't. I didn't notice the comment, lol. Go ahead, take it!

**Comment by ethmtrgt** [comment]
@ann0nip Thank you :)

**Comment by ethmtrgt** [comment]
@eduardconstantin, Hello again. I'm pretty unfamiliar with React, so I had some delay. Opened up a pull request just now. Feel free to review it. Thanks.

**Comment by eduardconstantin** [comment]
@ethmtrgt no worries, I am glad to see that you managed to do something
