### ISSUE TITLE
[Feature] Create contribution section

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Crypto-Rankings#5]
## Feature description

Add a contribution section to the readme file.
Also add a CONTRIBUTE.md file with contribution guidelines.

**Comment by 3t8** [comment]
I'd like to work on this

**Comment by eduardconstantin** [comment]
@3t8 could you also add a section for contributors?

**Comment by 3t8** [comment]
> @3t8 could you also add a section for contributors?

Wouldn't it be better to use something like https://allcontributors.org/docs/en/bot/overview ?

**Comment by eduardconstantin** [comment]
That's great! I'll implement that bot. Thank you!
